### PR TITLE
Update Manual_MrBayes_v3.2.tex

### PR DESCRIPTION
**Pull request by pablovaldes**
Fixed figure placed partially out of the margins of the page. Size of text in appendix increased to improve readability,
Also removing numeration of appendix in toc, and cleaning code.

### CODE REVIEW

**Review by nylander — APPROVED** [review]
These changes do make the insertion of Appendix_Fig?.pdf files much better, thank you so much for the contribution.

An outstanding issue is, however:

Just as in the previous (current develop) version, the Index made in the Manual_MrBayes_v3.2.pdf does not point to the correct pages for the chapter "Overview of Models and Moves" (points to p. 151, is actually p. 152), and Bibliography (also points to p.151, actual page is p.155). Will perhaps be a GH-Issue on its own.

**Comment by pablovaldes** [comment]
> the Index made in the Manual_MrBayes_v3.2.pdf does not point to the correct pages

Ok, I will fix it when reaching that part.

**Comment by andkaha** [comment]
As previous comments indicate that some things needs to be fixed, I'm delaying my approval and the merge a bit.

**Comment by pablovaldes** [comment]
The problem is not related with the proposed changes and is not trivial to solve. I have a likely culprit and could try a few things, but not now. I want to focus on other parts of the code first.

**Review by ronquist — APPROVED** [review]
These changes seem good to me!

**Pull request merged**
