### PR TITLE
Feature/issue 154

### PR DESCRIPTION
**Pull request by ronquist**
Fixes the parsimony model. Now the model runs for a single partition, at least. Running sumt and sump produces sensible output. Trees are saved as topology, without branch lengths.

### CODE REVIEW

**Comment by ronquist** [comment]
Refers to issue #154

**Comment by andkaha** [comment]
I tested the proposed fix with the example in issue #154 , but on both macOS and OpenBSD, it now generates a _Segmentation Fault_ rather than an error message from `mb`.

This is the stack trace I get in `gdb`:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000023ad9095ac5 in FlipSiteScalerSpace (m=0x23d82ce2000, chain=1) at ../../src/mcmc.c:4441
4441        temp = m->siteScalerIndex[chain];
Current language:  auto; currently minimal
(gdb) bt
#0  0x0000023ad9095ac5 in FlipSiteScalerSpace (m=0x23d82ce2000, chain=1) at ../../src/mcmc.c:4441
#1  0x0000023ad90b0801 in ResetFlips (chain=1) at ../../src/mcmc.c:15788
#2  0x0000023ad908c9b4 in RunChain (seed=0x7f7ffffc6158) at ../../src/mcmc.c:16993
#3  0x0000023ad908238e in DoMcmc () at ../../src/mcmc.c:2620
#4  0x0000023ad900e9e3 in ParseCommand (s=0x23d11114040 "    mcmc;\n") at ../../src/command.c:13976
#5  0x0000023ad9002f9b in DoExecute () at ../../src/command.c:3696
#6  0x0000023ad900e9e3 in ParseCommand (s=0x7f7ffffdec70 "Execute parsimodel.bug;")
    at ../../src/command.c:13976
#7  0x0000023ad8ff86fe in CommandLine (argc=2, argv=0x7f7fffff73d8) at ../../src/bayes.c:437
#8  0x0000023ad8ff63d4 in main (argc=2, argv=0x7f7fffff73d8) at ../../src/bayes.c:203
```

The error is due to dereferencing `NULL`:
```
(gdb) print m->siteScalerIndex
$1 = (int *) 0x0
```

**Comment by andkaha** [comment]
Further testing reveals that the _Segmentation Fault_ only occurs when MrBayes is compiled with Beagle support.

**Comment by ronquist** [comment]
Fixed the problem, which was due to a missing guard for the parsimony model when the beagle library was enabled. The code seems to work for me now.

**Pull request merged**
